version: '3.7'

services:
  frontend:
    init: true
    build:
      dockerfile: services/frontend-service/production.Dockerfile
      context: .
    container_name: frontend
    restart: always
    environment:
      - NODE_ENV=production
