version: '3.7'

services:
  packages-build:
    init: true
    build:
      dockerfile: ./packages/Dockerfile
      context: .
    container_name: packages-build
    volumes:
      - ./packages/:/home/node/packages/

  example:
    init: true
    depends_on: [packages-build]
    build:
      dockerfile: ./services/example/Dockerfile
      context: .
    ports:
      - '3000:3000'
      - '3001:3001'
      - '9229:9229'
    container_name: example
    volumes:
      - ./packages/core/:/home/node/packages/core/:cached
      - ./packages/react/:/home/node/packages/react/:cached
      - ./services/example/:/home/node/services/example/:delegated
    restart: always
    environment:
      - NODE_ENV=development
      - PORT=3000
      - ADDRESS=0.0.0.0

  editor-storybook:
    init: true
    depends_on: [packages-build]
    build:
      dockerfile: ./services/editor-storybook/Dockerfile
      context: .
    ports:
      - '3002:3002'
    container_name: editor-storybook
    volumes:
      - ./packages/react/:/home/node/packages/react/:cached
      - ./services/editor-storybook/:/home/node/services/editor-storybook/:delegated
    restart: always
