version: '3.7'

services:
  website:
    init: true
    build:
      dockerfile: services/website/production.Dockerfile
      context: .
    container_name: website
    restart: always
    environment:
      - NODE_ENV=production
