version: '3.7'

services:
  packages-build:
    init: true
    build:
      dockerfile: ./packages/Dockerfile
      context: .
    container_name: packages-build
    volumes:
      - ./packages/:/home/node/packages/

  website:
    init: true
    depends_on: [packages-build]
    build:
      dockerfile: ./services/website/development.Dockerfile
      context: .
    ports:
      - '3000:3000'
      - '3001:3001'
      - '9229:9229'
    container_name: website
    volumes:
      - ./packages/core/:/home/node/packages/core/:delegated
      - ./packages/website/:/home/node/packages/website/:delegated
      - ./services/website/:/home/node/services/website/:delegated
    restart: always
    environment:
      - NODE_ENV=development
      - PORT=3000
      - ADDRESS=0.0.0.0

  website-storybook:
    init: true
    depends_on: [packages-build]
    build:
      dockerfile: ./services/website-storybook/Dockerfile
      context: .
    ports:
      - '3002:3002'
    container_name: website-storybook
    volumes:
      - ./packages/website/:/home/node/packages/website/:delegated
      - ./services/website-storybook/:/home/node/services/website-storybook/:delegated
    restart: always
